# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6213f0be87e90c841f719d47be2493365bcdd7fffd0e64b27abdc7a17a80815529397bd9434c1c5249bc9c6098a90cfe238120917fd431f578e06d4feee2aacc

test:
  secret_key_base: b8659dca1b0bd6c441f7bdefe63273b351d0a8bb8ec43acd241a37596fc75bc4bfcbd86d6ef00f289946e419869e2ad35a0bbd04d8029871f38f3358bf4f25a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
